version: '3.0'

services:
  server-str:
    image: server-str
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-str
    networks:
      - backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres-str

  postgres-str:
    container_name: postgres-str
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/postgresdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

networks:
  backend:
    driver: bridge