## USERS

### GET ALL USERS
GET http://localhost:4000/users

### GET SINGLE USER
GET http://localhost:4000/users/0085aa92-a5ca-4424-a8f1-3ad57d583235

### ADD USER
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "12345",
    "login": "login1",
    "password": "password"
}

### UPDATE USER
PUT http://localhost:4000/users/0085aa92-a5ca-4424-a8f1-3ad57d583235
Content-Type: application/json

{
    "name": "1234",
    "login": "login",
    "password": "password"
}

### DELETE USER
DELETE  http://localhost:4000/users/1


## BOARDS

### GET ALL BOARDS
GET http://localhost:4000/boards

### GET SINGLE BOARD
GET http://localhost:4000/boards/ea347c9a-f769-4b4d-b687-015f5f5ec771

### ADD BOARD
POST http://localhost:4000/boards
Content-Type: application/json

{
    "columns": "1234",
    "login": "login",
    "password": "password"
}

### UPDATE BOARD
PUT http://localhost:4000/boards/62778dde-4abb-4cbb-a885-d70dc057ed97
Content-Type: application/json

{
    "title": "login"
}

### DELETE BOARD
DELETE  http://localhost:4000/boards/1


## TASKS

### GET ALL TASKS
GET http://localhost:4000/boards/4ebe4ee5-bc17-4a26-bf97-b9781c6fe6a6/tasks